name: Semgrep

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  Semgrep:
    name: Semgrep - Static Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Run Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: semgrep ci --code --max-target-bytes 50000000
